all:
  children:
    ol10_cis:
      hosts:
        oracle_remote:
          ansible_host: 68.221.16.169
          ansible_user: Oracle
          ansible_port: 22
          ansible_connection: ssh
          ansible_become: true
          ansible_become_method: sudo
          ansible_password: "{{ lookup('ansible.builtin.env', 'ORACLE_ANSIBLE_PASSWORD') }}"
          ansible_become_password: "{{ lookup('ansible.builtin.env', 'ORACLE_ANSIBLE_BECOME_PASSWORD') | default(lookup('ansible.builtin.env', 'ORACLE_ANSIBLE_PASSWORD'), true) }}"
          ansible_ssh_common_args: "-o PreferredAuthentications=password -o PubkeyAuthentication=no -o StrictHostKeyChecking=accept-new"
